require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AdvertisementTypesController do

  # This should return the minimal set of attributes required to create a valid
  # AdvertisementType. As you add validations to AdvertisementType, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all advertisement_types as @advertisement_types" do
      advertisement_type = AdvertisementType.create! valid_attributes
      get :index
      assigns(:advertisement_types).should eq([advertisement_type])
    end
  end

  describe "GET show" do
    it "assigns the requested advertisement_type as @advertisement_type" do
      advertisement_type = AdvertisementType.create! valid_attributes
      get :show, :id => advertisement_type.id
      assigns(:advertisement_type).should eq(advertisement_type)
    end
  end

  describe "GET new" do
    it "assigns a new advertisement_type as @advertisement_type" do
      get :new
      assigns(:advertisement_type).should be_a_new(AdvertisementType)
    end
  end

  describe "GET edit" do
    it "assigns the requested advertisement_type as @advertisement_type" do
      advertisement_type = AdvertisementType.create! valid_attributes
      get :edit, :id => advertisement_type.id
      assigns(:advertisement_type).should eq(advertisement_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AdvertisementType" do
        expect {
          post :create, :advertisement_type => valid_attributes
        }.to change(AdvertisementType, :count).by(1)
      end

      it "assigns a newly created advertisement_type as @advertisement_type" do
        post :create, :advertisement_type => valid_attributes
        assigns(:advertisement_type).should be_a(AdvertisementType)
        assigns(:advertisement_type).should be_persisted
      end

      it "redirects to the created advertisement_type" do
        post :create, :advertisement_type => valid_attributes
        response.should redirect_to(AdvertisementType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved advertisement_type as @advertisement_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        AdvertisementType.any_instance.stub(:save).and_return(false)
        post :create, :advertisement_type => {}
        assigns(:advertisement_type).should be_a_new(AdvertisementType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AdvertisementType.any_instance.stub(:save).and_return(false)
        post :create, :advertisement_type => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested advertisement_type" do
        advertisement_type = AdvertisementType.create! valid_attributes
        # Assuming there are no other advertisement_types in the database, this
        # specifies that the AdvertisementType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AdvertisementType.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => advertisement_type.id, :advertisement_type => {'these' => 'params'}
      end

      it "assigns the requested advertisement_type as @advertisement_type" do
        advertisement_type = AdvertisementType.create! valid_attributes
        put :update, :id => advertisement_type.id, :advertisement_type => valid_attributes
        assigns(:advertisement_type).should eq(advertisement_type)
      end

      it "redirects to the advertisement_type" do
        advertisement_type = AdvertisementType.create! valid_attributes
        put :update, :id => advertisement_type.id, :advertisement_type => valid_attributes
        response.should redirect_to(advertisement_type)
      end
    end

    describe "with invalid params" do
      it "assigns the advertisement_type as @advertisement_type" do
        advertisement_type = AdvertisementType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AdvertisementType.any_instance.stub(:save).and_return(false)
        put :update, :id => advertisement_type.id, :advertisement_type => {}
        assigns(:advertisement_type).should eq(advertisement_type)
      end

      it "re-renders the 'edit' template" do
        advertisement_type = AdvertisementType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AdvertisementType.any_instance.stub(:save).and_return(false)
        put :update, :id => advertisement_type.id, :advertisement_type => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested advertisement_type" do
      advertisement_type = AdvertisementType.create! valid_attributes
      expect {
        delete :destroy, :id => advertisement_type.id
      }.to change(AdvertisementType, :count).by(-1)
    end

    it "redirects to the advertisement_types list" do
      advertisement_type = AdvertisementType.create! valid_attributes
      delete :destroy, :id => advertisement_type.id
      response.should redirect_to(advertisement_types_url)
    end
  end

end
