require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AdvertiserTypesController do

  # This should return the minimal set of attributes required to create a valid
  # AdvertiserType. As you add validations to AdvertiserType, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all advertiser_types as @advertiser_types" do
      advertiser_type = AdvertiserType.create! valid_attributes
      get :index
      assigns(:advertiser_types).should eq([advertiser_type])
    end
  end

  describe "GET show" do
    it "assigns the requested advertiser_type as @advertiser_type" do
      advertiser_type = AdvertiserType.create! valid_attributes
      get :show, :id => advertiser_type.id
      assigns(:advertiser_type).should eq(advertiser_type)
    end
  end

  describe "GET new" do
    it "assigns a new advertiser_type as @advertiser_type" do
      get :new
      assigns(:advertiser_type).should be_a_new(AdvertiserType)
    end
  end

  describe "GET edit" do
    it "assigns the requested advertiser_type as @advertiser_type" do
      advertiser_type = AdvertiserType.create! valid_attributes
      get :edit, :id => advertiser_type.id
      assigns(:advertiser_type).should eq(advertiser_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AdvertiserType" do
        expect {
          post :create, :advertiser_type => valid_attributes
        }.to change(AdvertiserType, :count).by(1)
      end

      it "assigns a newly created advertiser_type as @advertiser_type" do
        post :create, :advertiser_type => valid_attributes
        assigns(:advertiser_type).should be_a(AdvertiserType)
        assigns(:advertiser_type).should be_persisted
      end

      it "redirects to the created advertiser_type" do
        post :create, :advertiser_type => valid_attributes
        response.should redirect_to(AdvertiserType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved advertiser_type as @advertiser_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        AdvertiserType.any_instance.stub(:save).and_return(false)
        post :create, :advertiser_type => {}
        assigns(:advertiser_type).should be_a_new(AdvertiserType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AdvertiserType.any_instance.stub(:save).and_return(false)
        post :create, :advertiser_type => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested advertiser_type" do
        advertiser_type = AdvertiserType.create! valid_attributes
        # Assuming there are no other advertiser_types in the database, this
        # specifies that the AdvertiserType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AdvertiserType.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => advertiser_type.id, :advertiser_type => {'these' => 'params'}
      end

      it "assigns the requested advertiser_type as @advertiser_type" do
        advertiser_type = AdvertiserType.create! valid_attributes
        put :update, :id => advertiser_type.id, :advertiser_type => valid_attributes
        assigns(:advertiser_type).should eq(advertiser_type)
      end

      it "redirects to the advertiser_type" do
        advertiser_type = AdvertiserType.create! valid_attributes
        put :update, :id => advertiser_type.id, :advertiser_type => valid_attributes
        response.should redirect_to(advertiser_type)
      end
    end

    describe "with invalid params" do
      it "assigns the advertiser_type as @advertiser_type" do
        advertiser_type = AdvertiserType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AdvertiserType.any_instance.stub(:save).and_return(false)
        put :update, :id => advertiser_type.id, :advertiser_type => {}
        assigns(:advertiser_type).should eq(advertiser_type)
      end

      it "re-renders the 'edit' template" do
        advertiser_type = AdvertiserType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AdvertiserType.any_instance.stub(:save).and_return(false)
        put :update, :id => advertiser_type.id, :advertiser_type => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested advertiser_type" do
      advertiser_type = AdvertiserType.create! valid_attributes
      expect {
        delete :destroy, :id => advertiser_type.id
      }.to change(AdvertiserType, :count).by(-1)
    end

    it "redirects to the advertiser_types list" do
      advertiser_type = AdvertiserType.create! valid_attributes
      delete :destroy, :id => advertiser_type.id
      response.should redirect_to(advertiser_types_url)
    end
  end

end
