require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DealTypesController do

  # This should return the minimal set of attributes required to create a valid
  # DealType. As you add validations to DealType, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all deal_types as @deal_types" do
      deal_type = DealType.create! valid_attributes
      get :index
      assigns(:deal_types).should eq([deal_type])
    end
  end

  describe "GET show" do
    it "assigns the requested deal_type as @deal_type" do
      deal_type = DealType.create! valid_attributes
      get :show, :id => deal_type.id
      assigns(:deal_type).should eq(deal_type)
    end
  end

  describe "GET new" do
    it "assigns a new deal_type as @deal_type" do
      get :new
      assigns(:deal_type).should be_a_new(DealType)
    end
  end

  describe "GET edit" do
    it "assigns the requested deal_type as @deal_type" do
      deal_type = DealType.create! valid_attributes
      get :edit, :id => deal_type.id
      assigns(:deal_type).should eq(deal_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DealType" do
        expect {
          post :create, :deal_type => valid_attributes
        }.to change(DealType, :count).by(1)
      end

      it "assigns a newly created deal_type as @deal_type" do
        post :create, :deal_type => valid_attributes
        assigns(:deal_type).should be_a(DealType)
        assigns(:deal_type).should be_persisted
      end

      it "redirects to the created deal_type" do
        post :create, :deal_type => valid_attributes
        response.should redirect_to(DealType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved deal_type as @deal_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        DealType.any_instance.stub(:save).and_return(false)
        post :create, :deal_type => {}
        assigns(:deal_type).should be_a_new(DealType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DealType.any_instance.stub(:save).and_return(false)
        post :create, :deal_type => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested deal_type" do
        deal_type = DealType.create! valid_attributes
        # Assuming there are no other deal_types in the database, this
        # specifies that the DealType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DealType.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => deal_type.id, :deal_type => {'these' => 'params'}
      end

      it "assigns the requested deal_type as @deal_type" do
        deal_type = DealType.create! valid_attributes
        put :update, :id => deal_type.id, :deal_type => valid_attributes
        assigns(:deal_type).should eq(deal_type)
      end

      it "redirects to the deal_type" do
        deal_type = DealType.create! valid_attributes
        put :update, :id => deal_type.id, :deal_type => valid_attributes
        response.should redirect_to(deal_type)
      end
    end

    describe "with invalid params" do
      it "assigns the deal_type as @deal_type" do
        deal_type = DealType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DealType.any_instance.stub(:save).and_return(false)
        put :update, :id => deal_type.id, :deal_type => {}
        assigns(:deal_type).should eq(deal_type)
      end

      it "re-renders the 'edit' template" do
        deal_type = DealType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DealType.any_instance.stub(:save).and_return(false)
        put :update, :id => deal_type.id, :deal_type => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested deal_type" do
      deal_type = DealType.create! valid_attributes
      expect {
        delete :destroy, :id => deal_type.id
      }.to change(DealType, :count).by(-1)
    end

    it "redirects to the deal_types list" do
      deal_type = DealType.create! valid_attributes
      delete :destroy, :id => deal_type.id
      response.should redirect_to(deal_types_url)
    end
  end

end
